import {
  Armchair,
  Boxes,
  Briefcase,
  Building2,
  ClipboardList,
  Cog,
  DoorOpen,
  Droplet,
  Factory,
  Fan,
  Flame,
  Hammer,
  HardHat,
  Landmark,
  LayoutGrid,
  Layers,
  Lightbulb,
  Megaphone,
  Monitor,
  Package,
  Paintbrush,
  Recycle,
  Ruler,
  Shield,
  ShieldCheck,
  Thermometer,
  Truck,
  Users,
  Warehouse,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

// Conjunto curado — não é o catálogo inteiro do lucide-react (~1500 ícones).
// Cobre os ícones usados pelas regras de categoria/material (guessMaterialIcon,
// migration 0005) mais uma expansão razoável para o seletor manual.
export const ICON_MAP: Record<string, LucideIcon> = {
  'layout-grid': LayoutGrid,
  'hard-hat': HardHat,
  users: Users,
  landmark: Landmark,
  monitor: Monitor,
  briefcase: Briefcase,
  megaphone: Megaphone,
  wrench: Wrench,
  zap: Zap,
  shield: Shield,
  armchair: Armchair,
  flame: Flame,
  paintbrush: Paintbrush,
  'door-open': DoorOpen,
  layers: Layers,
  droplet: Droplet,
  package: Package,
  truck: Truck,
  boxes: Boxes,
  hammer: Hammer,
  ruler: Ruler,
  'building-2': Building2,
  factory: Factory,
  'clipboard-list': ClipboardList,
  lightbulb: Lightbulb,
  fan: Fan,
  thermometer: Thermometer,
  recycle: Recycle,
  warehouse: Warehouse,
  cog: Cog,
  'shield-check': ShieldCheck,
}

export const ICON_OPTIONS = Object.keys(ICON_MAP)

export function getIconComponent(name: string): LucideIcon {
  return ICON_MAP[name] ?? Package
}
